# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cfe6d78551b098cc68ba4e288c5b55022cc15f641ed8e7709036360217d044352ab727dd39e521c872a1cd6086357b8b6080ccb5c279fe4be59686cefeb612a5

test:
  secret_key_base: 1c0dfff6f64a613b27e1e9d050d1fe1b307fbba206b79d7368345ff22822467f872f66764fe0f29dc13440fa6eb2a3583547ef1d4ae19c29c8efa9444dfd4bb1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
